// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

contract AutoGeneratedURINFT is ERC721 {
    string private _baseURIExtended;

    constructor() ERC721("AutoGeneratedURINFT", "AGN") {
        _baseURIExtended = "ipfs://QmBaseHash/";
    }

    function _baseURI() internal view override returns (string memory) {
        return _baseURIExtended;
    }

    function mint(uint256 tokenId) public {
        _safeMint(msg.sender, tokenId);
    }

    function tokenURI(uint256 tokenId) public view override returns (string memory) {
        require(ownerOf(tokenId) != address(0), "Gift does not exist");
        return string(abi.encodePacked(_baseURI(), Strings.toString(tokenId)));
    }
}
